### ISSUE TITLE
Broken "Security Report" link

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-site#2]
This link is broken: https://github.com/Granola-Team/mina-security-report

<img width="510" alt="image" src="https://github.com/Granola-Team/mina-site/assets/9849069/11bfe490-c38c-4bb9-9c32-32607e788fe0">

**Comment by robinbb** [comment]
It's actually correct for those who have access to the repo. I'll close this as "working as desired" for now. Eventually, we need a site overhaul.
